project:
  type: website
  output-dir: "docs"
  
website:
  title: "Thisuri Athukorala"
  favicon: "pic.jpg"
  
  page-footer: 
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      Contact [Thisuri Athukorala](mailto:thisurinima@gmail.com)
    background: "#004E4F"  
  
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Articles"
        file: Articles.qmd
      - text: "Resume"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/ThisuriNA
      - icon: linkedin
        href: https://linkedin.com/in/thisuri-athukorala
        

format:
  html:
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    theme:
      light: [cosmo, theme_light_custom.scss]
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"

editor: visual

